// <auto-generated />
using System;
using LifeOs.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LifeOS.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260221121248_AddedGoalsAndAchievements")]
    partial class AddedGoalsAndAchievements
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LifeOs.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("XPMultiplier")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColorHex = "#FF4B2B",
                            CreatedDate = new DateTime(2026, 2, 21, 12, 12, 47, 635, DateTimeKind.Utc).AddTicks(3941),
                            Icon = "fitness",
                            IsDeleted = false,
                            Name = "Physical",
                            XPMultiplier = 1.2
                        },
                        new
                        {
                            Id = 2,
                            ColorHex = "#AF40FF",
                            CreatedDate = new DateTime(2026, 2, 21, 12, 12, 47, 635, DateTimeKind.Utc).AddTicks(4569),
                            Icon = "school",
                            IsDeleted = false,
                            Name = "Learning",
                            XPMultiplier = 1.5
                        },
                        new
                        {
                            Id = 3,
                            ColorHex = "#2196F3",
                            CreatedDate = new DateTime(2026, 2, 21, 12, 12, 47, 635, DateTimeKind.Utc).AddTicks(4570),
                            Icon = "work",
                            IsDeleted = false,
                            Name = "Work",
                            XPMultiplier = 1.0
                        },
                        new
                        {
                            Id = 4,
                            ColorHex = "#4CAF50",
                            CreatedDate = new DateTime(2026, 2, 21, 12, 12, 47, 635, DateTimeKind.Utc).AddTicks(4571),
                            Icon = "groups",
                            IsDeleted = false,
                            Name = "Social",
                            XPMultiplier = 1.1000000000000001
                        },
                        new
                        {
                            Id = 5,
                            ColorHex = "#FFC107",
                            CreatedDate = new DateTime(2026, 2, 21, 12, 12, 47, 635, DateTimeKind.Utc).AddTicks(4572),
                            Icon = "self-improvement",
                            IsDeleted = false,
                            Name = "Mental",
                            XPMultiplier = 1.3
                        },
                        new
                        {
                            Id = 6,
                            ColorHex = "#E91E63",
                            CreatedDate = new DateTime(2026, 2, 21, 12, 12, 47, 635, DateTimeKind.Utc).AddTicks(4573),
                            Icon = "palette",
                            IsDeleted = false,
                            Name = "Creative",
                            XPMultiplier = 1.3999999999999999
                        });
                });

            modelBuilder.Entity("LifeOs.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrentLevelXP")
                        .HasColumnType("integer");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdentityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("NextLevelXP")
                        .HasColumnType("integer");

                    b.Property<int>("TotalXP")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentLevelXP = 0,
                            FullName = "Kerem Taşdemir",
                            IdentityId = "26867e6c-bb13-4843-a261-8d0e03e0d038",
                            Level = 1,
                            NextLevelXP = 1000,
                            TotalXP = 0
                        },
                        new
                        {
                            Id = 3,
                            CurrentLevelXP = 0,
                            FullName = "Zeynep Kaya",
                            IdentityId = "bot-002",
                            Level = 3,
                            NextLevelXP = 3000,
                            TotalXP = 2500
                        },
                        new
                        {
                            Id = 4,
                            CurrentLevelXP = 0,
                            FullName = "Mert Demir",
                            IdentityId = "bot-003",
                            Level = 1,
                            NextLevelXP = 1000,
                            TotalXP = 300
                        },
                        new
                        {
                            Id = 5,
                            CurrentLevelXP = 0,
                            FullName = "Selin Aydın",
                            IdentityId = "bot-004",
                            Level = 2,
                            NextLevelXP = 2000,
                            TotalXP = 1200
                        });
                });

            modelBuilder.Entity("LifeOs.Entities.UserActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("EarnedXP")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("UserActivities");
                });

            modelBuilder.Entity("LifeOs.Entities.UserActivity", b =>
                {
                    b.HasOne("LifeOs.Entities.Category", "Category")
                        .WithMany("UserActivities")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("LifeOs.Entities.Category", b =>
                {
                    b.Navigation("UserActivities");
                });
#pragma warning restore 612, 618
        }
    }
}
